version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-46-137-91-216.eu-west-1.compute.amazonaws.com
            database: d360kr8tefh941
            # schema: public
            user: cppgazrvfplobf
            password: 5ae94996868f6147abd29c7d320cfb538ed03f474fe360966c57498054602181
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
